name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
      - main
  workflow_dispatch:

jobs:
  hello:
on:
  push:
    branches:
      - main
  pull_request:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run: echo "Hi there"
        shell: bash

  goodbye:
    runs_on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Gooood bye everyone"
        shell: bash    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run: echo "Hi there"
        shell: bash

  goodbye:
    runs_on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Gooood bye everyone"
        shell: bash
