name: learn-github-actions
run-name: ${{github.actor}} is learning github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World	
        run: echo "Hi Everyone"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye
        run: echo "Bye everyone"
        shell: bash	 	  
